### PR TITLE
Datasources

### PR DESCRIPTION
**Pull request by reggev**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/hkubectl/26)

### CODE REVIEW

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkubectl/26)* status: all files reviewed, 1 unresolved discussion (waiting on @reggev)

___
*[commands/datasource/index.js, line 1 at r1](https://reviewable.io/reviews/kube-hpc/hkubectl/26#-MScbR7I2dpJ32W0vQtK:-MScbR7I2dpJ32W0vQtL:b67iis3) ([raw file](https://github.com/kube-hpc/hkubectl/blob/5ddd068c54a14f249c0f241a753752acba5034d3/commands/datasource/index.js#L1)):*
> ```JavaScript
> const { parse } = require('path');
> ```

I would prefer to keep the actual handlers in separate files (like all other commands)

**Review by reggev — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkubectl/26)* status: 7 of 11 files reviewed, 1 unresolved discussion (waiting on @yehiyam)

___
*[commands/datasource/index.js, line 1 at r1](https://reviewable.io/reviews/kube-hpc/hkubectl/26#-MScbR7I2dpJ32W0vQtK:-MScjE9X-AmnSq4_SjrL:b-896fix) ([raw file](https://github.com/kube-hpc/hkubectl/blob/5ddd068c54a14f249c0f241a753752acba5034d3/commands/datasource/index.js#L1)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

I would prefer to keep the actual handlers in separate files (like all other commands)
</blockquote></details>

Done.

**Review by reggev — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkubectl/26#-:-MT5E6e1EYB5VbQwEVyX:bnfp4nl)* status: 6 of 13 files reviewed, 1 unresolved discussion (waiting on @yehiyam)

**Review by yehiyam — APPROVED** [review]
> Reviewed 4 of 4 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkubectl/26)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @reggev)

**Pull request merged**
