### PR TITLE
Import between env feature

### PR DESCRIPTION
**Pull request by mkkCoder**
contains import and export all, algorithms, pipelines + indexes and ctl commands +import/export utils

- - -
This change is [Reviewable](https://reviewable.io/reviews/kube-HPC/hkubectl/62)

### CODE REVIEW

**Review by golanha — CHANGES_REQUESTED** [review]
1. Don't put defatults for folders input and output.
2. Make folders parameter mandatory (Better put a prameter wihch is not a flag). Prompt for it if missing.
3. Make reuse of code when invoking import all, use code from import pipeline and algrorithms.

> Reviewed 11 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkubectl/62#-:-NoQIglY4dr99YusAu8S:b-drp7s7)* status: 11 of 18 files reviewed, 12 unresolved discussions (waiting on @mkkCoder)

___
*[`package-lock.json` line 3458 at r1](https://reviewable.io/reviews/kube-HPC/hkubectl/62#-NoGbtYb9BjtqTUsweCz:-NoGbtYb9BjtqTUsweD-:b-lss9rt) ([raw file](https://github.com/kube-HPC/hkubectl/blob/7f45a8b783e0bbbaf8f2647b9d6ac656aa026f69/package-lock.json#L3458)):*
> ```JSON
>         "minimist": "^1.2.5",
>         "multistream": "^4.1.0",
>         "pkg-get": "3.2.6",
> ```

looks like a change you made by mistake while replacing fetcth with get, 
I don't think the package-lock.json should be modified at all
___
*[`commands/export/algorithms.js` line 45 at r1](https://reviewable.io/reviews/kube-HPC/hkubectl/62#-NoH9mdi2kT_8VcTx7Jn:-NoH9mdi2kT_8VcTx7Jo:bpqob0j) ([raw file](https://github.com/kube-HPC/hkubectl/blob/7f45a8b783e0bbbaf8f2647b9d6ac656aa026f69/commands/export/algorithms.js#L45)):*
> ```JavaScript
> }
> 
> module.exports = {
> ```

Put the exported object in a variable and export the variable.



_Code quote:_
```JavaScript
module.exports = {
```
___
*[`commands/export/pipelines.js` line 15 at r1](https://reviewable.io/reviews/kube-HPC/hkubectl/62#-NoQFjfR25cXVsi2pP5N:-NoQFjfR25cXVsi2pP5O:b-k6k0k2) ([raw file](https://github.com/kube-HPC/hkubectl/blob/7f45a8b783e0bbbaf8f2647b9d6ac656aa026f69/commands/export/pipelines.js#L15)):*
> ```JavaScript
>         try {
>             await fs.promises.access(outputDirectory);
>         }
> ```

duplicate line



_Code quote:_
```JavaScript
        await fs.promises.access(outputDirectory);

        try {
            await fs.promises.access(outputDirectory);
        }
```
___
*[`commands/export/pipelines.js` line 19 at r1](https://reviewable.io/reviews/kube-HPC/hkubectl/62#-NoQCwG58Ts2Tb1cw6e3:-NoQCwG58Ts2Tb1cw6e4:bu1fjqf) ([raw file](https://github.com/kube-HPC/hkubectl/blob/7f45a8b783e0bbbaf8f2647b9d6ac656aa026f69/commands/export/pipelines.js#L19)):*
> ```JavaScript
>             console.error(`Error accessing directory: ${err.message}`);
>         }
>         for (const file of data) {
> ```

pipeline



_Code quote:_
```JavaScript
file
```
___
*[`commands/export/pipelines.js` line 76 at r1](https://reviewable.io/reviews/kube-HPC/hkubectl/62#-NoQDTzt9tjnewFrEceM:-NoQDTzt9tjnewFrEceN:b-32w8e1) ([raw file](https://github.com/kube-HPC/hkubectl/blob/7f45a8b783e0bbbaf8f2647b9d6ac656aa026f69/commands/export/pipelines.js#L76)):*
> ```JavaScript
>         }
>         catch (error) {
>             console.error('Error geting and saving pipelines:', error.message);
> ```

Error during export pipelines



_Code quote:_
```JavaScript
Error geting and saving pipelines:
```
___
*[`commands/import/algorithms.js` line 10 at r1](https://reviewable.io/reviews/kube-HPC/hkubectl/62#-NoQH2Fd9kHLMXX87UFu:-NoQH2Fe6fMHFrBb2QN_:bfc7ezb) ([raw file](https://github.com/kube-HPC/hkubectl/blob/7f45a8b783e0bbbaf8f2647b9d6ac656aa026f69/commands/import/algorithms.js#L10)):*
> ```JavaScript
> 
>     try {
>         await fs.promises.access(inputDirectory);
> ```

give specific erorr if directory does not exist



_Code quote:_
```JavaScript
await fs.promises.access(inputDirectory);
```
___
*[`commands/import/algorithms.js` line 71 at r1](https://reviewable.io/reviews/kube-HPC/hkubectl/62#-NoQGvBRBOzK--MZY1XM:-NoQGvBRBOzK--MZY1XN:b-ecbl2r) ([raw file](https://github.com/kube-HPC/hkubectl/blob/7f45a8b783e0bbbaf8f2647b9d6ac656aa026f69/commands/import/algorithms.js#L71)):*
> ```JavaScript
>     }
>     catch (error) {
>         console.error(`Error importing files: ${error.message}`);
> ```

Error importing algrithms



_Code quote:_
```JavaScript
`Error importing file
```
___
*[`commands/import/all.js` line 99 at r1](https://reviewable.io/reviews/kube-HPC/hkubectl/62#-NoQHSyP-7ppYTjiKuiA:-NoQHSyP-7ppYTjiKuiB:b6ursi0) ([raw file](https://github.com/kube-HPC/hkubectl/blob/7f45a8b783e0bbbaf8f2647b9d6ac656aa026f69/commands/import/all.js#L99)):*
> ```JavaScript
>     }
>     catch (error) {
>         console.error(`Error importing files: ${error.message}`);
> ```

Error during import all



_Code quote:_
```JavaScript
Error importing files
```
___
*[`commands/import/all.js` line 111 at r1](https://reviewable.io/reviews/kube-HPC/hkubectl/62#-NoQOMOv0puZktSxINwP:-NoQOMOv0puZktSxINwQ:bicuzxm) ([raw file](https://github.com/kube-HPC/hkubectl/blob/7f45a8b783e0bbbaf8f2647b9d6ac656aa026f69/commands/import/all.js#L111)):*
> ```JavaScript
>             describe: 'path/of/your/directory',
>             type: 'string'
>         });
> ```

This is never used



_Code quote:_
```JavaScript
        yargs.positional('directory', {
            demandOption: 'Please provide the directory to import the algorithms from',
            describe: 'path/of/your/directory',
            type: 'string'
        });
```
___
*[`commands/import/all.js` line 134 at r1](https://reviewable.io/reviews/kube-HPC/hkubectl/62#-NoQHpvd3iopRdWeK61g:-NoQHpvd3iopRdWeK61h:b5rrr00) ([raw file](https://github.com/kube-HPC/hkubectl/blob/7f45a8b783e0bbbaf8f2647b9d6ac656aa026f69/commands/import/all.js#L134)):*
> ```JavaScript
>         catch (error) {
>             console.error('Error importing files:', error.message);
>         }
> ```

importData is already srounded with try catch



_Code quote:_
```JavaScript
        catch (error) {
            console.error('Error importing files:', error.message);
        }
```
___
*[`commands/import/pipelines.js` line 51 at r1](https://reviewable.io/reviews/kube-HPC/hkubectl/62#-NoQO4v0-VdfPI8jeM82:-NoQO4v0-VdfPI8jeM83:b2z8xtd) ([raw file](https://github.com/kube-HPC/hkubectl/blob/7f45a8b783e0bbbaf8f2647b9d6ac656aa026f69/commands/import/pipelines.js#L51)):*
> ```JavaScript
>     }
>     catch (error) {
>         console.error(`Error importing files: ${error.message}`);
> ```

Error importing pipelines



_Code quote:_
```JavaScript
Error importing files
```
___
*[`utils/importUtils.js` line 66 at r1](https://reviewable.io/reviews/kube-HPC/hkubectl/62#-NoQKUYH6C2f_QzmW8pr:-NoQKUYH6C2f_QzmW8ps:b-aeetkb) ([raw file](https://github.com/kube-HPC/hkubectl/blob/7f45a8b783e0bbbaf8f2647b9d6ac656aa026f69/utils/importUtils.js#L66)):*
> ```JavaScript
> 
>         // eslint-disable-next-line no-param-reassign
>         fileContent = fileContent.replace(regex, newValue);
> ```

use replaceAll to replace all ocourances not just the first one.



_Code quote:_
```JavaScript
replace
```

**Review by mkkCoder — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkubectl/62)* status: 8 of 18 files reviewed, 12 unresolved discussions (waiting on @golanha)

___
*[`package-lock.json` line 3458 at r1](https://reviewable.io/reviews/kube-HPC/hkubectl/62#-NoGbtYb9BjtqTUsweCz:-NoRi7DsB1tjVu2th_5J:b-896fix) ([raw file](https://github.com/kube-HPC/hkubectl/blob/7f45a8b783e0bbbaf8f2647b9d6ac656aa026f69/package-lock.json#L3458)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

looks like a change you made by mistake while replacing fetcth with get, 
I don't think the package-lock.json should be modified at all
</blockquote></details>

Done.
___
*[`commands/export/algorithms.js` line 45 at r1](https://reviewable.io/reviews/kube-HPC/hkubectl/62#-NoH9mdi2kT_8VcTx7Jn:-NoRiAGKCVRijuRWAc8h:b-896fix) ([raw file](https://github.com/kube-HPC/hkubectl/blob/7f45a8b783e0bbbaf8f2647b9d6ac656aa026f69/commands/export/algorithms.js#L45)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

Put the exported object in a variable and export the variable.
</blockquote></details>

Done.
___
*[`commands/export/pipelines.js` line 15 at r1](https://reviewable.io/reviews/kube-HPC/hkubectl/62#-NoQFjfR25cXVsi2pP5N:-NoRiAwQ9JIK-slmtv1K:b-896fix) ([raw file](https://github.com/kube-HPC/hkubectl/blob/7f45a8b783e0bbbaf8f2647b9d6ac656aa026f69/commands/export/pipelines.js#L15)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

duplicate line
</blockquote></details>

Done.
___
*[`commands/export/pipelines.js` line 19 at r1](https://reviewable.io/reviews/kube-HPC/hkubectl/62#-NoQCwG58Ts2Tb1cw6e3:-NoRiC8sCEhDFQyqQEUF:b-896fix) ([raw file](https://github.com/kube-HPC/hkubectl/blob/7f45a8b783e0bbbaf8f2647b9d6ac656aa026f69/commands/export/pipelines.js#L19)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

pipeline
</blockquote></details>

Done.
___
*[`commands/export/pipelines.js` line 76 at r1](https://reviewable.io/reviews/kube-HPC/hkubectl/62#-NoQDTzt9tjnewFrEceM:-NoRiR7QCmhwu7duVumZ:b-896fix) ([raw file](https://github.com/kube-HPC/hkubectl/blob/7f45a8b783e0bbbaf8f2647b9d6ac656aa026f69/commands/export/pipelines.js#L76)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

Error during export pipelines
</blockquote></details>

Done.
___
*[`commands/import/algorithms.js` line 10 at r1](https://reviewable.io/reviews/kube-HPC/hkubectl/62#-NoQH2Fd9kHLMXX87UFu:-NoRjpQ75VaAa_qsUWd0:b-896fix) ([raw file](https://github.com/kube-HPC/hkubectl/blob/7f45a8b783e0bbbaf8f2647b9d6ac656aa026f69/commands/import/algorithms.js#L10)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

give specific erorr if directory does not exist
</blockquote></details>

Done.
___
*[`commands/import/algorithms.js` line 71 at r1](https://reviewable.io/reviews/kube-HPC/hkubectl/62#-NoQGvBRBOzK--MZY1XM:-NoRkGwb6VFo6BwmBl4v:b-896fix) ([raw file](https://github.com/kube-HPC/hkubectl/blob/7f45a8b783e0bbbaf8f2647b9d6ac656aa026f69/commands/import/algorithms.js#L71)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

Error importing algrithms
</blockquote></details>

Done.
___
*[`commands/import/all.js` line 99 at r1](https://reviewable.io/reviews/kube-HPC/hkubectl/62#-NoQHSyP-7ppYTjiKuiA:-NoRkTY05jaN7yOKHyXw:b-896fix) ([raw file](https://github.com/kube-HPC/hkubectl/blob/7f45a8b783e0bbbaf8f2647b9d6ac656aa026f69/commands/import/all.js#L99)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

Error during import all
</blockquote></details>

Done.
___
*[`commands/import/all.js` line 111 at r1](https://reviewable.io/reviews/kube-HPC/hkubectl/62#-NoQOMOv0puZktSxINwP:-NoRkZlx-E3w2azAeLoK:b-896fix) ([raw file](https://github.com/kube-HPC/hkubectl/blob/7f45a8b783e0bbbaf8f2647b9d6ac656aa026f69/commands/import/all.js#L111)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

This is never used
</blockquote></details>

Done.
___
*[`commands/import/all.js` line 134 at r1](https://reviewable.io/reviews/kube-HPC/hkubectl/62#-NoQHpvd3iopRdWeK61g:-NoRkyhh9RDJT3QDKDbA:b-896fix) ([raw file](https://github.com/kube-HPC/hkubectl/blob/7f45a8b783e0bbbaf8f2647b9d6ac656aa026f69/commands/import/all.js#L134)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

importData is already srounded with try catch
</blockquote></details>

Done.
___
*[`commands/import/pipelines.js` line 51 at r1](https://reviewable.io/reviews/kube-HPC/hkubectl/62#-NoQO4v0-VdfPI8jeM82:-NoRkn6YE95U9vpjOSLS:b-896fix) ([raw file](https://github.com/kube-HPC/hkubectl/blob/7f45a8b783e0bbbaf8f2647b9d6ac656aa026f69/commands/import/pipelines.js#L51)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

Error importing pipelines
</blockquote></details>

Done.
___
*[`utils/importUtils.js` line 66 at r1](https://reviewable.io/reviews/kube-HPC/hkubectl/62#-NoQKUYH6C2f_QzmW8pr:-NoRlyjc-sAMye4tVVjw:b-u8b559) ([raw file](https://github.com/kube-HPC/hkubectl/blob/7f45a8b783e0bbbaf8f2647b9d6ac656aa026f69/utils/importUtils.js#L66)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

use replaceAll to replace all ocourances not just the first one.
</blockquote></details>

Using the 'g' flag. The global flag ensures that all occurrences of the pattern in the input string are replaced, not just the first one. code: const regex \= new RegExp(oldValue, 'g');

**Review by golanha — CHANGES_REQUESTED** [review]
> Reviewed 2 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkubectl/62)* status: 10 of 18 files reviewed, 15 unresolved discussions (waiting on @mkkCoder)

___
*[`commands/export/all.js` line 16 at r3](https://reviewable.io/reviews/kube-HPC/hkubectl/62#-NoS66NH5AdMvLgrHxb0:-NoS66NH5AdMvLgrHxb1:b-sjcch3) ([raw file](https://github.com/kube-HPC/hkubectl/blob/79ffa1b62a7d65173ef40d6a18e12a08481054ff/commands/export/all.js#L16)):*
> ```JavaScript
>             fs.mkdirSync(outputPipelineDirectory, { recursive: true });
>             console.log(`Folder "${outputPipelineDirectory}" created.`);
>         }
> ```

move check directory exists in to exportPipelinedata



_Code quote:_
```JavaScript
        if (!fs.existsSync(outputDirectory)) {
            console.error(`Folder "${outputPipelineDirectory}" does not exist.`);
        }
        else {
            fs.mkdirSync(outputPipelineDirectory, { recursive: true });
            console.log(`Folder "${outputPipelineDirectory}" created.`);
        }
```
___
*[`commands/export/all.js` line 26 at r3](https://reviewable.io/reviews/kube-HPC/hkubectl/62#-NoS6UUv8ujvS2J7wDyq:-NoS6UUv8ujvS2J7wDyr:bejg8k4) ([raw file](https://github.com/kube-HPC/hkubectl/blob/79ffa1b62a7d65173ef40d6a18e12a08481054ff/commands/export/all.js#L26)):*
> ```JavaScript
>             fs.mkdirSync(outputAlgorithmsDirectory, { recursive: true });
>             console.log(`Folder "${outputAlgorithmsDirectory}" created.`);
>         }
> ```

move check directory exists into exportAlgorithmData



_Code quote:_
```JavaScript
        if (!fs.existsSync(outputDirectory)) {
            console.error(`Folder "${outputAlgorithmsDirectory}" does not exist.`);
        }
        else {
            fs.mkdirSync(outputAlgorithmsDirectory, { recursive: true });
            console.log(`Folder "${outputAlgorithmsDirectory}" created.`);
        }
```
___
*[`commands/export/pipelines.js` line 19 at r1](https://reviewable.io/reviews/kube-HPC/hkubectl/62#-NoQCwG58Ts2Tb1cw6e3:-NoS-Elf6b0tnwmyphJo:b-q5una1) ([raw file](https://github.com/kube-HPC/hkubectl/blob/7f45a8b783e0bbbaf8f2647b9d6ac656aa026f69/commands/export/pipelines.js#L19)):*
<details><summary><i>Previously, mkkCoder wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I meant to change the const file to pipeline
___
*[`commands/export/pipelines.js` line 20 at r3](https://reviewable.io/reviews/kube-HPC/hkubectl/62#-NoS9HSr45-EXZtnTdq7:-NoS9HSr45-EXZtnTdq8:bfm6o60) ([raw file](https://github.com/kube-HPC/hkubectl/blob/79ffa1b62a7d65173ef40d6a18e12a08481054ff/commands/export/pipelines.js#L20)):*
> ```JavaScript
>         }
>         catch (err) {
>             console.error(`Error accessing directory: ${err.message}`);
> ```

        if (!fs.existsSync(outputDirectory)) {
            console.error(`Folder "${outputPipelineDirectory}" does not exist.`);
          return;
        }
add the return so you won't fail on other things later



_Code quote:_
```JavaScript
Error accessing directory
```
___
*[`commands/import/pipelines.js` line 10 at r3](https://reviewable.io/reviews/kube-HPC/hkubectl/62#-NoS7z1A3x0aVVc63qE7:-NoS7z1A3x0aVVc63qE8:bpq4jf) ([raw file](https://github.com/kube-HPC/hkubectl/blob/79ffa1b62a7d65173ef40d6a18e12a08481054ff/commands/import/pipelines.js#L10)):*
> ```JavaScript
> 
>     try {
>         await fs.promises.access(inputDirectory);
> ```

message if directory does not exist



_Code quote:_
```JavaScript
   await fs.promises.access(inputDirectory);
```

**Review by mkkCoder — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkubectl/62)* status: 9 of 18 files reviewed, 15 unresolved discussions (waiting on @golanha)

___
*[`commands/export/all.js` line 16 at r3](https://reviewable.io/reviews/kube-HPC/hkubectl/62#-NoS66NH5AdMvLgrHxb0:-Nof6zKCDjropJsV7kJG:b-896fix) ([raw file](https://github.com/kube-HPC/hkubectl/blob/79ffa1b62a7d65173ef40d6a18e12a08481054ff/commands/export/all.js#L16)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

move check directory exists in to exportPipelinedata
</blockquote></details>

Done.
___
*[`commands/export/all.js` line 26 at r3](https://reviewable.io/reviews/kube-HPC/hkubectl/62#-NoS6UUv8ujvS2J7wDyq:-Nof7-5LAwONSssPzJ7r:b-896fix) ([raw file](https://github.com/kube-HPC/hkubectl/blob/79ffa1b62a7d65173ef40d6a18e12a08481054ff/commands/export/all.js#L26)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

move check directory exists into exportAlgorithmData
</blockquote></details>

Done.
___
*[`commands/export/pipelines.js` line 19 at r1](https://reviewable.io/reviews/kube-HPC/hkubectl/62#-NoQCwG58Ts2Tb1cw6e3:-Nof1aJI7HU65w7x-vSP:b-896fix) ([raw file](https://github.com/kube-HPC/hkubectl/blob/7f45a8b783e0bbbaf8f2647b9d6ac656aa026f69/commands/export/pipelines.js#L19)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

I meant to change the const file to pipeline
</blockquote></details>

Done.
___
*[`commands/export/pipelines.js` line 20 at r3](https://reviewable.io/reviews/kube-HPC/hkubectl/62#-NoS9HSr45-EXZtnTdq7:-Nof7-vb4_07IBxXYocy:b-896fix) ([raw file](https://github.com/kube-HPC/hkubectl/blob/79ffa1b62a7d65173ef40d6a18e12a08481054ff/commands/export/pipelines.js#L20)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

if (!fs.existsSync(outputDirectory)) {
            console.error(`Folder "${outputPipelineDirectory}" does not exist.`);
          return;
        }
add the return so you won't fail on other things later
</blockquote></details>

Done.
___
*[`commands/import/pipelines.js` line 10 at r3](https://reviewable.io/reviews/kube-HPC/hkubectl/62#-NoS7z1A3x0aVVc63qE7:-Nof2YG04uQ-0416J-Co:b-896fix) ([raw file](https://github.com/kube-HPC/hkubectl/blob/79ffa1b62a7d65173ef40d6a18e12a08481054ff/commands/import/pipelines.js#L10)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

message if directory does not exist
</blockquote></details>

Done.

**Review by golanha — CHANGES_REQUESTED** [review]
> Reviewed 2 of 18 files at r1, 1 of 8 files at r2, 1 of 4 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkubectl/62)* status: 17 of 18 files reviewed, 10 unresolved discussions (waiting on @mkkCoder)

___
*[`commands/export/algorithms.js` line 45 at r1](https://reviewable.io/reviews/kube-HPC/hkubectl/62#-NoH9mdi2kT_8VcTx7Jn:-Nofwf4p3W36P6g9irUN:b-ghyphg) ([raw file](https://github.com/kube-HPC/hkubectl/blob/7f45a8b783e0bbbaf8f2647b9d6ac656aa026f69/commands/export/algorithms.js#L45)):*
<details><summary><i>Previously, mkkCoder wrote…</i></summary><blockquote>

Done.
</blockquote></details>

not done yet
___
*[`commands/import/pipelines.js` line 13 at r4](https://reviewable.io/reviews/kube-HPC/hkubectl/62#-Nofx5097nMTem5UTZcy:-Nofx5097nMTem5UTZcz:b-7qvkdq) ([raw file](https://github.com/kube-HPC/hkubectl/blob/189fd2a58386875d91cc26e048adf3d4c805eebd/commands/import/pipelines.js#L13)):*
> ```JavaScript
>     }
>     catch (error) {
>         console.error(`directory '${inputDirectory}' does not exists: ${error.message}`);
> ```

exist



_Code quote:_
```JavaScript
 exists
```

**Review by mkkCoder — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkubectl/62)* status: 11 of 18 files reviewed, 6 unresolved discussions (waiting on @golanha)

___
*[`commands/export/algorithms.js` line 45 at r1](https://reviewable.io/reviews/kube-HPC/hkubectl/62#-NoH9mdi2kT_8VcTx7Jn:-NokVKA18a9AxusAGaQE:b-g8zol2) ([raw file](https://github.com/kube-HPC/hkubectl/blob/7f45a8b783e0bbbaf8f2647b9d6ac656aa026f69/commands/export/algorithms.js#L45)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

not done yet
</blockquote></details>

exporting as a variable is possible only if it is a builder. in this case its is a command
___
*[`commands/import/pipelines.js` line 13 at r4](https://reviewable.io/reviews/kube-HPC/hkubectl/62#-Nofx5097nMTem5UTZcy:-NofzpME9vOibn6pfcgI:b-896fix) ([raw file](https://github.com/kube-HPC/hkubectl/blob/189fd2a58386875d91cc26e048adf3d4c805eebd/commands/import/pipelines.js#L13)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

exist
</blockquote></details>

Done.

**Review by golanha — APPROVED** [review]
> Reviewed 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkubectl/62)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mkkCoder)

**Comment by mkkCoder** [comment]
merged

**Pull request merged**
