### PR TITLE
Added sync start

### PR DESCRIPTION
**Pull request by RonShvarz**
kube-HPC/hkube#1887

Added sync function to use with existing algorithms

- - -
This change is [Reviewable](https://reviewable.io/reviews/kube-HPC/hkubectl/66)

### CODE REVIEW

**Review by golanha — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkubectl/66)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @RonShvarz)

___
*[`commands/sync/start.js` line 16 at r1](https://reviewable.io/reviews/kube-HPC/hkubectl/66#-Nr4BIrF7bWjE3CO2nWc:-Nr4BIrF7bWjE3CO2nWd:b-ojvfo3) ([raw file](https://github.com/kube-HPC/hkubectl/blob/39a628a13cd025d607cc0e05271a0652e13b8396/commands/sync/start.js#L16)):*
> ```JavaScript
>     if (res.result.error || res.error) {
>         let msg;
>         if (res.result.error.code === 400) {
> ```

Check for the specific error message to know that the reason for the failure is that the algorithm doesn't exsist, 400 is still general.



_Code quote:_
```JavaScript
res.result.error.code === 400
```
___
*[`commands/sync/start.js` line 61 at r1](https://reviewable.io/reviews/kube-HPC/hkubectl/66#-Nr4CekYCmYzACvDBRTT:-Nr4CekYCmYzACvDBRTU:bjxvhu0) ([raw file](https://github.com/kube-HPC/hkubectl/blob/39a628a13cd025d607cc0e05271a0652e13b8396/commands/sync/start.js#L61)):*
> ```JavaScript
>             describe: 'base image for the algorithm',
>             type: 'string'
>         }
> ```

why do we need these parameters?



_Code quote:_
```JavaScript
        env: {
            describe: 'algorithm runtime environment',
            type: 'string',
            choices: ['python', 'nodejs']

        },
        entryPoint: {
            describe: 'the main file of the algorithm',
            type: 'string',
            alias: ['e']
        },
        baseImage: {
            describe: 'base image for the algorithm',
            type: 'string'
        }
```

**Review by RonShvarz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkubectl/66)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @golanha)

___
*[`commands/sync/start.js` line 16 at r1](https://reviewable.io/reviews/kube-HPC/hkubectl/66#-Nr4BIrF7bWjE3CO2nWc:-Nr4W-LQAfI4yxz-OLVI:b-be2qji) ([raw file](https://github.com/kube-HPC/hkubectl/blob/39a628a13cd025d607cc0e05271a0652e13b8396/commands/sync/start.js#L16)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

Check for the specific error message to know that the reason for the failure is that the algorithm doesn't exsist, 400 is still general.
</blockquote></details>

Api server's update function concats many required base parameters depending on what is missing from the body,

"return {

error: {

name: options.name,

code: 400,

message: \`Error updating ${options.name} ${error.message}\`

}

};"

If there requierments change in the future, and i check for their existance in a stream-wise operation, it might not be future proof. Your opinion ?
___
*[`commands/sync/start.js` line 61 at r1](https://reviewable.io/reviews/kube-HPC/hkubectl/66#-Nr4CekYCmYzACvDBRTT:-Nr4VubpDaA0gc3yMSnN:bkmo6th) ([raw file](https://github.com/kube-HPC/hkubectl/blob/39a628a13cd025d607cc0e05271a0652e13b8396/commands/sync/start.js#L61)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

why do we need these parameters?
</blockquote></details>

Forgot to cleanup after we decided not to invoke watch from the start function. done

**Review by golanha — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkubectl/66)* status: all files reviewed, 2 unresolved discussions (waiting on @RonShvarz)

___
*[`commands/sync/start.js` line 32 at r4](https://reviewable.io/reviews/kube-HPC/hkubectl/66#-Nr4rtxc8i_T4fpHLcdu:-Nr4rtxc8i_T4fpHLcdv:b-7qlapa) ([raw file](https://github.com/kube-HPC/hkubectl/blob/e3b48d82b8c55b0f9f84fbc28e224bd8852f548e/commands/sync/start.js#L32)):*
> ```JavaScript
>         algorithmName: {
>             demandOption: true,
>             describe: 'The name of the algorithm to sync data into',
> ```

files



_Code quote:_
```JavaScript
data
```
___
*[`commands/sync/stop.js` line 30 at r4](https://reviewable.io/reviews/kube-HPC/hkubectl/66#-Nr4rfNk83eZRsl1jvb8:-Nr4rfNk83eZRsl1jvb9:b-8rvpg5) ([raw file](https://github.com/kube-HPC/hkubectl/blob/e3b48d82b8c55b0f9f84fbc28e224bd8852f548e/commands/sync/stop.js#L30)):*
> ```JavaScript
>         algorithmName: {
>             demandOption: true,
>             describe: 'The name of the algorithm to sync data into',
> ```

The name of the algorithm to stop syncing files into.



_Code quote:_
```JavaScript
The name of the algorithm to sync data into
```

**Review by RonShvarz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkubectl/66)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @golanha)

___
*[`commands/sync/start.js` line 32 at r4](https://reviewable.io/reviews/kube-HPC/hkubectl/66#-Nr4rtxc8i_T4fpHLcdu:-Nr4uG-T-o8nWnksb7Nj:b-896fix) ([raw file](https://github.com/kube-HPC/hkubectl/blob/e3b48d82b8c55b0f9f84fbc28e224bd8852f548e/commands/sync/start.js#L32)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

files
</blockquote></details>

Done.
___
*[`commands/sync/stop.js` line 30 at r4](https://reviewable.io/reviews/kube-HPC/hkubectl/66#-Nr4rfNk83eZRsl1jvb8:-Nr4uGN82mqu28Hdht9A:b-896fix) ([raw file](https://github.com/kube-HPC/hkubectl/blob/e3b48d82b8c55b0f9f84fbc28e224bd8852f548e/commands/sync/stop.js#L30)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

The name of the algorithm to stop syncing files into.
</blockquote></details>

Done.

**Pull request merged**
